// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//import 'firebase_options.dart';

//await Firebase.initializeApp(
//  options: DefaultFirebaseOptions.currentPlatform,
//);

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxUKKZazAzBunEZkJ8KLdsqAevlOmIol8',
    appId: '1:173318853383:web:c9b2576ec870b597c02ba2',
    messagingSenderId: '173318853383',
    projectId: 'mtd-app-2022',
    authDomain: 'mtd-app-2022.firebaseapp.com',
    databaseURL:
        'https://mtd-app-2022-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mtd-app-2022.appspot.com',
    measurementId: 'G-K4BKDFDQHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3k-wKS8HWjFMu92KeXtdYMZrb3NZhh2c',
    appId: '1:173318853383:android:a648c4bb2a721ef7c02ba2',
    messagingSenderId: '173318853383',
    projectId: 'mtd-app-2022',
    databaseURL:
        'https://mtd-app-2022-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mtd-app-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARFXycHtdSCAl7DsCMeFEPx0krKhXBveI',
    appId: '1:173318853383:ios:ef9d2b551246f15dc02ba2',
    messagingSenderId: '173318853383',
    projectId: 'mtd-app-2022',
    databaseURL:
        'https://mtd-app-2022-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mtd-app-2022.appspot.com',
    iosClientId:
        '173318853383-parr5mcfgsapn2e0bu9tua40agm4vd8c.apps.googleusercontent.com',
    iosBundleId: 'dev.widdyjp.mountsOfTheWorld',
  );
}
